version: '3.8'

services:
  app:
    build: .
    command:
      bash -c "
      sleep 3
      && ./run_cron.sh"
    volumes:
      - .:/app
      - ./trembita.log:/var/log/trembita.log
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: